version: '3'
services:
  db:
    image: keinos/sqlite3
    tty: true
    stdin_open: true
    volumes: 
    - dbdata:/var/lib/sqlite3/data
    environment:
    - .env
  web:
    build: .
    volumes: 
    - webdata:/app
    ports: 
    - "3000:3000"
    depends_on:
    - db
volumes:
  dbdata:
  webdata:

